# Generated by Django 3.0.8 on 2021-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(default='Genearlist', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
