# Generated by Django 3.0.8 on 2021-06-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Immunology', 'Immunology'), ('Anesthesiology', 'Anesthesiology'), ('Emergency', 'Emergency')], default='Generalist', max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Doctor'),
        ),
    ]
